# Generated by Django 2.0.2 on 2018-03-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('blog_title', models.CharField(max_length=100)),
                ('blog_about', models.CharField(max_length=100)),
                ('blog_content', models.TextField()),
                ('user_id', models.CharField(max_length=32)),
                ('is_delete', models.SmallIntegerField(blank=True)),
                ('creater', models.CharField(max_length=32)),
                ('create_date', models.DateTimeField()),
                ('updater', models.CharField(blank=True, max_length=32)),
                ('update_date', models.DateTimeField(blank=True)),
                ('remark', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('blog_id', models.CharField(max_length=32)),
                ('comment_content', models.TextField()),
                ('user_id', models.CharField(max_length=32)),
                ('is_delete', models.SmallIntegerField(blank=True)),
                ('creater', models.CharField(max_length=32)),
                ('create_date', models.DateTimeField()),
                ('updater', models.CharField(blank=True, max_length=32)),
                ('update_date', models.DateTimeField(blank=True)),
                ('remark', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('true_name', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=16)),
                ('sex', models.SmallIntegerField()),
                ('age', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('address', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=30)),
                ('is_delete', models.SmallIntegerField(blank=True)),
                ('creater', models.CharField(max_length=32)),
                ('create_date', models.DateTimeField()),
                ('updater', models.CharField(blank=True, max_length=32)),
                ('update_date', models.DateTimeField(blank=True)),
                ('remark', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
